<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
    <RootNamespace>WireFish.Unit</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <LibraryReference Include="Novolis.Avalonia.Layout" />
    <PackageReference Include="TUnit" />
    <ProjectReference Include="..\..\src\WireFish\WireFish.csproj" />
  </ItemGroup>
</Project>

