<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>Novolis.RoboSharpPlayer</RootNamespace>
    <AssemblyName>Novolis.RoboSharpPlayer</AssemblyName>
    <Description>Run and inspect RoboSharp source programs.</Description>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <LibraryReference Include="Novolis.Language.RoboSharp" />
  </ItemGroup>
</Project>
